name: Build Ticket Grabber

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --noconfirm --onefile --windowed --manifest app.manifest --name "抢票工具_Windows" ticket_grabber.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicketGrabber-Windows
          path: dist/抢票工具_Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build application
        run: pyinstaller --noconfirm --onefile --windowed --name "抢票工具_macOS" ticket_grabber.py

      - name: Package .app into a .zip
        run: zip -r "抢票工具_macOS.zip" "dist/抢票工具_macOS.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicketGrabber-macOS
          path: "抢票工具_macOS.zip"
